services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true

    HealthChecksBundle\Controller\HealthController:
        tags:
            - { name: container.service_subscriber }

    HealthChecksBundle\Controller\PingController:
        tags:
            - { name: container.service_subscriber }

    health_checks.mongodb_connection_check:
        class: HealthChecksBundle\Check\MongoDbConnectionCheck
        arguments: [ '@service_container' ]

    health_checks.doctrine_check:
        class: HealthChecksBundle\Check\DoctrineCheck
        arguments: [ '@service_container' ]
