services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true

    Ringostat\HealthChecksBundle\Controller\HealthController:
        tags:
            - { name: container.service_subscriber }

    Ringostat\HealthChecksBundle\Controller\PingController:
        tags:
            - { name: container.service_subscriber }

    health_checks.mongodb_connection_check:
        class: Ringostat\HealthChecksBundle\Check\MongoDbConnectionCheck
        arguments: [ '@service_container' ]
