services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true

    SymfonyHealthCheckBundle\Controller\HealthController:
        tags:
            - { name: container.service_subscriber }

    SymfonyHealthCheckBundle\Controller\PingController:
        tags:
            - { name: container.service_subscriber }

    symfony_health_check.mongodb_connection_check:
        class: SymfonyHealthCheckBundle\Check\MongoDbConnectionCheck
        arguments: [ '@service_container' ]

    symfony_health_check.doctrine_check:
        class: SymfonyHealthCheckBundle\Check\DoctrineCheck
        arguments: [ '@service_container' ]
